### makemore: lect02

### day02
- 202403010815-202403010830
- 202403011945-202403012100
- 2024030120000-202403012300

- ### day03
- 202403020800-?
- 

### Pointers:

Eric Z Yang’s blog:

- http://blog.ezyang.com/

- Tensor Strided Representation

In [52]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [53]:
words = open("./names.txt").read().splitlines()

In [54]:
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [55]:
len(words)

32033

In [56]:
chars = sorted(list(set("".join(words))))
chars[:10]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [57]:
stoi = {s: i + 1 for i, s in enumerate(chars)}
stoi["."] = 0
itos = {i: s for s, i in stoi.items()}

In [58]:
# stoi
# itos

In [74]:
### build data sets

block_size = 3
X, Y = [], []

for word in words[:5]:
    context = [0] * block_size
    print(word)
    
    for ch in word + ".":
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print("".join(itos[i] for i in context), "--->", itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [77]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [78]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [79]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [80]:
C = torch.randn((27, 2))

In [81]:
C

tensor([[-0.4744,  0.7216],
        [-0.9487, -0.8000],
        [ 0.4537, -3.0191],
        [ 0.1287, -1.7270],
        [-0.0439, -0.5544],
        [ 2.4251, -0.1251],
        [-0.0438,  0.7654],
        [ 0.6402, -1.3654],
        [-0.3708, -0.3797],
        [-0.3447,  0.7677],
        [ 0.3931, -0.3144],
        [ 0.4578, -1.1474],
        [-0.9143, -0.7136],
        [ 0.0492,  0.1445],
        [ 1.6787,  0.6750],
        [-0.9416, -0.0752],
        [ 0.5075, -1.3170],
        [-1.7448, -0.1277],
        [-0.0877, -0.2872],
        [ 0.2627,  0.1032],
        [ 0.4249,  0.8055],
        [-1.1823, -1.7941],
        [ 0.0478, -1.5242],
        [ 1.6902,  0.2003],
        [-0.9371,  0.2127],
        [ 0.5555,  0.1077],
        [ 2.6906, -0.2119]])

In [82]:
C[5]

tensor([ 2.4251, -0.1251])

In [87]:
F.one_hot(torch.tensor(5), num_classes=27).float()

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
F.one_hot(torch.tensor(5), num_classes=27).shape

torch.Size([27])

In [90]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C

tensor([ 2.4251, -0.1251])

In [92]:
C[[5, 6, 7]]

tensor([[ 2.4251, -0.1251],
        [-0.0438,  0.7654],
        [ 0.6402, -1.3654]])

In [93]:
C[6]

tensor([-0.0438,  0.7654])

In [95]:
C[torch.tensor([5, 6, 7, 7, 7, 7])]

tensor([[ 2.4251, -0.1251],
        [-0.0438,  0.7654],
        [ 0.6402, -1.3654],
        [ 0.6402, -1.3654],
        [ 0.6402, -1.3654],
        [ 0.6402, -1.3654]])

In [97]:
X[13]

tensor([0, 0, 1])

In [98]:
X[13, 2]

tensor(1)

In [99]:
X[13][2]

tensor(1)

In [100]:
C[X]

tensor([[[-0.4744,  0.7216],
         [-0.4744,  0.7216],
         [-0.4744,  0.7216]],

        [[-0.4744,  0.7216],
         [-0.4744,  0.7216],
         [ 2.4251, -0.1251]],

        [[-0.4744,  0.7216],
         [ 2.4251, -0.1251],
         [ 0.0492,  0.1445]],

        [[ 2.4251, -0.1251],
         [ 0.0492,  0.1445],
         [ 0.0492,  0.1445]],

        [[ 0.0492,  0.1445],
         [ 0.0492,  0.1445],
         [-0.9487, -0.8000]],

        [[-0.4744,  0.7216],
         [-0.4744,  0.7216],
         [-0.4744,  0.7216]],

        [[-0.4744,  0.7216],
         [-0.4744,  0.7216],
         [-0.9416, -0.0752]],

        [[-0.4744,  0.7216],
         [-0.9416, -0.0752],
         [-0.9143, -0.7136]],

        [[-0.9416, -0.0752],
         [-0.9143, -0.7136],
         [-0.3447,  0.7677]],

        [[-0.9143, -0.7136],
         [-0.3447,  0.7677],
         [ 0.0478, -1.5242]],

        [[-0.3447,  0.7677],
         [ 0.0478, -1.5242],
         [-0.3447,  0.7677]],

        [[ 0.0478, -1

In [103]:
C[X][2]

tensor([[-0.4744,  0.7216],
        [ 2.4251, -0.1251],
        [ 0.0492,  0.1445]])

In [104]:
X[2]

tensor([ 0,  5, 13])

In [106]:
C[0], C[5], C[13]

(tensor([-0.4744,  0.7216]),
 tensor([ 2.4251, -0.1251]),
 tensor([0.0492, 0.1445]))

In [112]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [111]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [113]:
emb @ W1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (96x2 and 6x100)

In [121]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], dim=1).shape

torch.Size([32, 6])

In [126]:
torch.cat(torch.unbind(emb, 1), dim=1).shape

torch.Size([32, 6])

In [127]:
torch.cat(torch.unbind(emb, 1), dim=1)

tensor([[-0.4744,  0.7216, -0.4744,  0.7216, -0.4744,  0.7216],
        [-0.4744,  0.7216, -0.4744,  0.7216,  2.4251, -0.1251],
        [-0.4744,  0.7216,  2.4251, -0.1251,  0.0492,  0.1445],
        [ 2.4251, -0.1251,  0.0492,  0.1445,  0.0492,  0.1445],
        [ 0.0492,  0.1445,  0.0492,  0.1445, -0.9487, -0.8000],
        [-0.4744,  0.7216, -0.4744,  0.7216, -0.4744,  0.7216],
        [-0.4744,  0.7216, -0.4744,  0.7216, -0.9416, -0.0752],
        [-0.4744,  0.7216, -0.9416, -0.0752, -0.9143, -0.7136],
        [-0.9416, -0.0752, -0.9143, -0.7136, -0.3447,  0.7677],
        [-0.9143, -0.7136, -0.3447,  0.7677,  0.0478, -1.5242],
        [-0.3447,  0.7677,  0.0478, -1.5242, -0.3447,  0.7677],
        [ 0.0478, -1.5242, -0.3447,  0.7677, -0.9487, -0.8000],
        [-0.4744,  0.7216, -0.4744,  0.7216, -0.4744,  0.7216],
        [-0.4744,  0.7216, -0.4744,  0.7216, -0.9487, -0.8000],
        [-0.4744,  0.7216, -0.9487, -0.8000,  0.0478, -1.5242],
        [-0.9487, -0.8000,  0.0478, -1.5

In [133]:
h = emb.view(32, 6) @ W1 + b1
h

tensor([[ 0.2698, -0.2570,  0.0895,  ...,  0.0267,  0.1985, -0.0917],
        [-1.2305, -3.6760, -7.1495,  ...,  3.4769, -2.7044,  2.1311],
        [-0.5600, -5.6757, -1.5486,  ...,  4.0364,  5.0867, -0.8809],
        ...,
        [-2.4665,  1.4699,  0.1548,  ...,  1.9567, -1.8205, -1.2081],
        [ 0.2877, -2.0989,  0.8532,  ..., -1.7007, -0.0994, -1.3158],
        [ 0.0527,  2.4705,  1.2806,  ...,  0.9542,  0.4257, -2.3375]])

In [138]:
h = emb.view(-1, 6) @ W1 + b1
h

tensor([[ 0.2698, -0.2570,  0.0895,  ...,  0.0267,  0.1985, -0.0917],
        [-1.2305, -3.6760, -7.1495,  ...,  3.4769, -2.7044,  2.1311],
        [-0.5600, -5.6757, -1.5486,  ...,  4.0364,  5.0867, -0.8809],
        ...,
        [-2.4665,  1.4699,  0.1548,  ...,  1.9567, -1.8205, -1.2081],
        [ 0.2877, -2.0989,  0.8532,  ..., -1.7007, -0.0994, -1.3158],
        [ 0.0527,  2.4705,  1.2806,  ...,  0.9542,  0.4257, -2.3375]])

In [139]:
h.shape

torch.Size([32, 100])

In [140]:
h = torch.tanh(h)

In [141]:
h

tensor([[ 0.2634, -0.2515,  0.0892,  ...,  0.0267,  0.1959, -0.0914],
        [-0.8427, -0.9987, -1.0000,  ...,  0.9981, -0.9911,  0.9722],
        [-0.5080, -1.0000, -0.9136,  ...,  0.9994,  0.9999, -0.7069],
        ...,
        [-0.9857,  0.8996,  0.1536,  ...,  0.9608, -0.9489, -0.8361],
        [ 0.2800, -0.9704,  0.6927,  ..., -0.9355, -0.0991, -0.8657],
        [ 0.0526,  0.9858,  0.8567,  ...,  0.7417,  0.4017, -0.9815]])

In [142]:
W2 = torch.randn(100, 27)
b2 = torch.randn(27)

In [144]:
logits = h @ W2 + b2
logits

tensor([[-10.8086, -10.7209,  -3.2213,  -0.4693,   0.2651,   8.0094,  -8.3593,
           3.5509,   1.7258,   3.5028,  -1.1415,  15.4472,   3.9035,  -4.5180,
          -0.4433,   0.3306,  10.7860,  -2.3146,   2.6501, -12.6710,  -2.0273,
          -8.5216,  -3.7138,   7.3099,   2.1047,   3.4749,   8.5081],
        [ -7.7757,   0.4486,  -4.3645,  -3.2403,   5.3058,  -4.6408,   3.3070,
           9.4848, -11.7334,   0.4897, -10.0873,   2.8587,  -7.8081,  -0.2923,
          -2.4009,  -2.5167,   0.2766,  -7.8080,  11.5716,   1.8728,  -8.3241,
          -9.8096,   7.4581,  13.5573, -14.9467,  18.4819,   5.5386],
        [ -0.4338,   0.0386,  -1.1960, -10.1666,   4.3487,  14.1850,   6.8001,
          13.1170, -10.1367,  -2.6699,   9.0791,  -4.6856,   0.9090,   9.3327,
          14.8807,  -1.4159,  16.8974,  -9.1267,  -1.8273,  -1.6719,   4.8151,
          -6.0724,   7.0305,  -7.9309,  -8.2510,   7.4024, -15.9183],
        [ -7.5997,  -6.7872,  -0.1264,  -4.4635,  -7.5167, -12.8549,  -5.6128,


In [145]:
logits.shape

torch.Size([32, 27])

In [147]:
counts = logits.exp()

In [159]:
probs = counts / counts.sum(dim=0)

In [166]:
counts.sum(dim=0)

tensor([1.6113e+04, 7.6699e+05, 1.0670e+05, 1.4927e+01, 1.0959e+06, 1.6661e+06,
        1.0943e+03, 5.1834e+05, 3.1882e+05, 3.3493e+06, 1.9236e+07, 1.9570e+08,
        1.0321e+05, 3.3559e+07, 2.9023e+06, 4.9465e+02, 2.8738e+07, 5.8997e+02,
        1.4653e+08, 9.1411e+00, 7.7324e+06, 8.0834e+01, 7.0670e+06, 6.3138e+06,
        2.9870e+08, 9.3470e+08, 2.4381e+05])

In [168]:
# counts.sum(dim=1)

In [162]:
probs.shape

torch.Size([32, 27])

In [164]:
probs[0]

tensor([1.2552e-09, 2.8788e-11, 3.7395e-07, 4.1899e-02, 1.1895e-06, 1.8062e-03,
        2.1402e-07, 6.7226e-05, 1.7618e-05, 9.9153e-06, 1.6602e-08, 2.6124e-02,
        4.8032e-04, 3.2512e-10, 2.2118e-07, 2.8136e-03, 1.6820e-03, 1.6748e-04,
        9.6604e-08, 3.4360e-07, 1.7030e-08, 2.4632e-06, 3.4506e-09, 2.3678e-04,
        2.7468e-08, 3.4551e-08, 2.0321e-02])

In [188]:
probs = counts / counts.sum(dim=1, keepdim=True)

In [189]:
probs.shape

torch.Size([32, 27])

In [165]:
probs[0]

tensor([1.2552e-09, 2.8788e-11, 3.7395e-07, 4.1899e-02, 1.1895e-06, 1.8062e-03,
        2.1402e-07, 6.7226e-05, 1.7618e-05, 9.9153e-06, 1.6602e-08, 2.6124e-02,
        4.8032e-04, 3.2512e-10, 2.2118e-07, 2.8136e-03, 1.6820e-03, 1.6748e-04,
        9.6604e-08, 3.4360e-07, 1.7030e-08, 2.4632e-06, 3.4506e-09, 2.3678e-04,
        2.7468e-08, 3.4551e-08, 2.0321e-02])

In [193]:
probs[0].sum(), probs[1].sum(), probs[2].sum()

(tensor(1.0000), tensor(1.0000), tensor(1.))

In [177]:
a = torch.tensor([[1, 2, 5], [4, 5, 1]])

In [187]:
a

tensor([[1, 2, 5],
        [4, 5, 1]])

In [186]:
a.shape

torch.Size([2, 3])

In [179]:
a.sum(dim=0)

tensor([5, 7, 6])

In [180]:
a.sum(dim=1)

tensor([ 8, 10])

In [183]:
a.sum(dim=1, keepdim=True)

tensor([[ 8],
        [10]])

In [181]:
a / a.sum(dim=0)

tensor([[0.2000, 0.2857, 0.8333],
        [0.8000, 0.7143, 0.1667]])

In [191]:
a / a.sum(dim=1, keepdim=True)

tensor([[0.1250, 0.2500, 0.6250],
        [0.4000, 0.5000, 0.1000]])

In [195]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [196]:
probs[torch.arange(32), Y]

tensor([5.8199e-04, 6.9637e-09, 4.2377e-04, 1.4970e-11, 1.8354e-08, 2.6917e-07,
        1.5949e-06, 2.8370e-05, 8.8229e-09, 2.2256e-05, 3.8493e-06, 2.3092e-04,
        4.2703e-12, 2.0886e-10, 1.1217e-10, 2.9493e-07, 6.4228e-06, 1.1595e-12,
        6.2411e-10, 4.5105e-08, 8.1945e-08, 3.5746e-12, 4.3652e-11, 6.6913e-09,
        1.6584e-07, 6.0744e-13, 6.8777e-08, 1.5622e-03, 2.7982e-09, 1.4383e-10,
        8.6175e-12, 1.4154e-08])

In [201]:
loss = - probs[torch.arange(32), Y].log().mean()
loss

tensor(17.7407)

In [206]:
g = torch.Generator().manual_seed(2147483647)
g

In [210]:
C = torch.randn((27, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 27), generator=g)
b2 = torch.randn(27, generator=g)
params = [C, W1, b1, W2, b2]

In [214]:
sum(p.nelement() for p in params)

3481

In [216]:
X.shape

torch.Size([32, 3])

In [224]:
emb = C[X] # (32, 3, 2)
h = emb.view(-1, 6) @ W1 + b1 # (32, 100)
h = torch.tanh(h) # (32, 100)
logits = h @ W2 + b2 # (27, 100)
conunts = logits.exp()
probs = counts / counts.sum(dim=1, keepdim=True)
loss = - probs[torch.arange(32), Y].log().mean()
loss

tensor(17.7407)

In [239]:
logits.shape, counts.shape, probs.shape

(torch.Size([32, 27]), torch.Size([32, 27]), torch.Size([32, 27]))

In [236]:
logits[0]

tensor([  1.3223,  -7.2362,  23.0069,  -8.5653,  -3.6574,  15.8683,   7.1421,
         -5.4376,   6.2788,  -2.7974,   7.0352,  -6.2685,   7.0912,  -5.6868,
         -6.1072, -16.0000,  15.9964,  -6.5898,   3.7228,   9.7217,  -6.9711,
         11.7096,  -4.3727,  -0.6997,  11.7734,  -2.6304,  -8.5238])

In [237]:
counts[0]

tensor([2.0225e-05, 2.2080e-05, 3.9901e-02, 6.2541e-01, 1.3036e+00, 3.0092e+03,
        2.3421e-04, 3.4846e+01, 5.6170e+00, 3.3209e+01, 3.1935e-01, 5.1126e+06,
        4.9574e+01, 1.0911e-02, 6.4193e-01, 1.3918e+00, 4.8338e+04, 9.8810e-02,
        1.4156e+01, 3.1408e-06, 1.3169e-01, 1.9911e-04, 2.4385e-02, 1.4950e+03,
        8.2047e+00, 3.2295e+01, 4.9546e+03])

In [238]:
probs[0]

tensor([3.9115e-12, 4.2703e-12, 7.7170e-09, 1.2096e-07, 2.5211e-07, 5.8199e-04,
        4.5297e-11, 6.7393e-06, 1.0863e-06, 6.4228e-06, 6.1763e-08, 9.8879e-01,
        9.5877e-06, 2.1102e-09, 1.2415e-07, 2.6917e-07, 9.3487e-03, 1.9110e-08,
        2.7378e-06, 6.0744e-13, 2.5468e-08, 3.8508e-11, 4.7161e-09, 2.8913e-04,
        1.5868e-06, 6.2459e-06, 9.5823e-04])

In [228]:
probs[0].sum(), probs[1].sum()

(tensor(1.0000), tensor(1.0000))

In [254]:
probs.shape

torch.Size([32, 27])

In [240]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [243]:
probs[torch.arange(32), Y]

tensor([5.8199e-04, 6.9637e-09, 4.2377e-04, 1.4970e-11, 1.8354e-08, 2.6917e-07,
        1.5949e-06, 2.8370e-05, 8.8229e-09, 2.2256e-05, 3.8493e-06, 2.3092e-04,
        4.2703e-12, 2.0886e-10, 1.1217e-10, 2.9493e-07, 6.4228e-06, 1.1595e-12,
        6.2411e-10, 4.5105e-08, 8.1945e-08, 3.5746e-12, 4.3652e-11, 6.6913e-09,
        1.6584e-07, 6.0744e-13, 6.8777e-08, 1.5622e-03, 2.7982e-09, 1.4383e-10,
        8.6175e-12, 1.4154e-08])

In [244]:
probs[torch.arange(32), Y].sum()

tensor(0.0029)

In [258]:
probs[torch.arange(32), Y]

tensor([5.8199e-04, 6.9637e-09, 4.2377e-04, 1.4970e-11, 1.8354e-08, 2.6917e-07,
        1.5949e-06, 2.8370e-05, 8.8229e-09, 2.2256e-05, 3.8493e-06, 2.3092e-04,
        4.2703e-12, 2.0886e-10, 1.1217e-10, 2.9493e-07, 6.4228e-06, 1.1595e-12,
        6.2411e-10, 4.5105e-08, 8.1945e-08, 3.5746e-12, 4.3652e-11, 6.6913e-09,
        1.6584e-07, 6.0744e-13, 6.8777e-08, 1.5622e-03, 2.7982e-09, 1.4383e-10,
        8.6175e-12, 1.4154e-08])

In [247]:
- probs[torch.arange(32), Y].log().mean()

tensor(17.7407)

In [253]:
logits[0]

tensor([  1.3223,  -7.2362,  23.0069,  -8.5653,  -3.6574,  15.8683,   7.1421,
         -5.4376,   6.2788,  -2.7974,   7.0352,  -6.2685,   7.0912,  -5.6868,
         -6.1072, -16.0000,  15.9964,  -6.5898,   3.7228,   9.7217,  -6.9711,
         11.7096,  -4.3727,  -0.6997,  11.7734,  -2.6304,  -8.5238])

In [260]:
F.cross_entropy(logits, Y)

tensor(19.8155)

In [251]:
logits.min(), logits.max()

(tensor(-26.4824), tensor(25.6139))

In [262]:
F.softmax(logits).shape

/tmp/ipykernel_138511/4195890328.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(logits).shape


torch.Size([32, 27])

In [263]:
F.cross_entropy(F.softmax(logits), Y)

/tmp/ipykernel_138511/4280729900.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.cross_entropy(F.softmax(logits), Y)


tensor(3.3512)

/tmp/ipykernel_138511/4280729900.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.cross_entropy(F.softmax(logits), Y)


tensor(3.3512)

In [232]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [234]:
# torch.nn.CrossEntropyLoss(logits, Y)

### day03 20240302

`logits` are the same if we add an offset `logits` + `t`

without offset:

$\logit = [x]$ 

$\counts = [e^x]$ 

$\probs = [e^x / \sum e^x]$ 


with offset $t$:

$\logit' = [x + t]$ 

$\counts' = [e^{x + t}]$ 

$\probs' = [e^{x + t} / \sum e^{x + t}] = [e^x / \sum e^x]$ 



### Here we examine `cross-entropy`

In [336]:
import torch
import torch.nn.functional as F

# Example logits (output from model)
logits = torch.tensor([[1.2, 0.5, -0.3],
                       [-0.1, 2.0, 0.8]])

# Example target labels
targets = torch.tensor([0, 2])

# Calculate cross-entropy loss
loss = F.cross_entropy(logits, targets)

print(loss.item())  # Print the scalar value of the loss


1.0476915836334229


---
Note that:

- the most (least) probable index in `row = 0` is `ind = 0` (`ind = 2`) with the score value 1.2 (-0.3), respect.;

- the most (least) probable index in `row  = 1` is `ind = 1` (`ind = 0`) with the score value 2.0 (-0.1), respect.

---

Here we examine that:

In [354]:
import torch
import torch.nn.functional as F

# Example logits (output from model)
logits = torch.tensor([[1.2, 0.5, -0.3],
                       [-0.1, 2.0, 0.8]])

for i, logit in enumerate(logits):
    print("-" * 50)
    print(f"row: {i}")
    for j, _ in enumerate(logit):
        # Example target labels
        target = torch.tensor(j)
        # Calculate cross-entropy loss
        loss = F.cross_entropy(logit, target).item()
        print(f"({i}, {j}): {loss = }")

--------------------------------------------------
row: 0
(0, 0): loss = 0.5421587824821472
(0, 1): loss = 1.2421588897705078
(0, 2): loss = 2.042158842086792
--------------------------------------------------
row: 1
(1, 0): loss = 2.4532244205474854
(1, 1): loss = 0.35322442650794983
(1, 2): loss = 1.5532244443893433


### compare with soft-max:

In [359]:
import torch
import torch.nn.functional as F

# Example logits (output from model)
logits = torch.tensor([[1.2, 0.5, -0.3],
                       [-0.1, 2.0, 0.8]])

# Example target labels
targets = torch.tensor([0, 2])

# Calculate cross-entropy loss
loss1 = F.cross_entropy(logits, targets)
print(loss1.item())  # Print the scalar value of the loss

1.0476915836334229


In [360]:
loss2 = F.cross_entropy(F.softmax(logits), targets)
print(loss2.item())  # Print the scalar value of the loss

1.0627484321594238


/tmp/ipykernel_138511/4264976145.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  loss2 = F.cross_entropy(F.softmax(logits), targets)


***DO NOT ENTER `SOFTMAX` INTO `CROSS-ENTROPY`; BUT `LOGITS` I.E. SCORES***